// Code generated by wsdl2go. DO NOT EDIT.

package wsdl

import (
	"github.com/fiorix/wsdl2go/soap"
)

// Namespace was auto-generated from WSDL.
var Namespace = "http://jws.back.hb.org.cn/"

// NewHbcaService creates an initializes a HbcaService.
func NewHbcaService(cli *soap.Client) HbcaService {
	return &hbcaService{cli}
}

// HbcaService was auto-generated from WSDL
// and defines interface for the remote service. Useful for testing.
type HbcaService interface {
	// CreateP10 was auto-generated from WSDL.
	CreateP10(CreateP10 *CreateP10) (*CreateP10Response, error)

	// CreateP10ForUpdate was auto-generated from WSDL.
	CreateP10ForUpdate(CreateP10ForUpdate *CreateP10ForUpdate) (*CreateP10ForUpdateResponse, error)

	// CreateTimeStamp was auto-generated from WSDL.
	CreateTimeStamp(CreateTimeStamp *CreateTimeStamp) (*CreateTimeStampResponse, error)

	// CreateTimeStampRequest was auto-generated from WSDL.
	CreateTimeStampRequest(CreateTimeStampRequest *CreateTimeStampRequest) (*CreateTimeStampRequestResponse, error)

	// DecryptEnvelop was auto-generated from WSDL.
	DecryptEnvelop(DecryptEnvelop *DecryptEnvelop) (*DecryptEnvelopResponse, error)

	// DeleteEncCert was auto-generated from WSDL.
	DeleteEncCert(DeleteEncCert *DeleteEncCert) (*DeleteEncCertResponse, error)

	// DeleteSignCert was auto-generated from WSDL.
	DeleteSignCert(DeleteSignCert *DeleteSignCert) (*DeleteSignCertResponse, error)

	// EncryptEnvelop was auto-generated from WSDL.
	EncryptEnvelop(EncryptEnvelop *EncryptEnvelop) (*EncryptEnvelopResponse, error)

	// GenRandom was auto-generated from WSDL.
	GenRandom(GenRandom *GenRandom) (*GenRandomResponse, error)

	// GetEncCert was auto-generated from WSDL.
	GetEncCert(GetEncCert *GetEncCert) (*GetEncCertResponse, error)

	// GetSealImage was auto-generated from WSDL.
	GetSealImage(GetSealImage *GetSealImage) (*GetSealImageResponse, error)

	// GetServerCert was auto-generated from WSDL.
	GetServerCert(GetServerCert *GetServerCert) (*GetServerCertResponse, error)

	// GetServerCertEx was auto-generated from WSDL.
	GetServerCertEx(GetServerCertEx *GetServerCertEx) (*GetServerCertExResponse, error)

	// GetSignCert was auto-generated from WSDL.
	GetSignCert(GetSignCert *GetSignCert) (*GetSignCertResponse, error)

	// Hello was auto-generated from WSDL.
	Hello(Hello *Hello) (*HelloResponse, error)

	// ImportEncCert was auto-generated from WSDL.
	ImportEncCert(ImportEncCert *ImportEncCert) (*ImportEncCertResponse, error)

	// ImportEncCertForUpdate was auto-generated from WSDL.
	ImportEncCertForUpdate(ImportEncCertForUpdate *ImportEncCertForUpdate) (*ImportEncCertForUpdateResponse, error)

	// ImportSignCert was auto-generated from WSDL.
	ImportSignCert(ImportSignCert *ImportSignCert) (*ImportSignCertResponse, error)

	// ImportSignCertForUpdate was auto-generated from WSDL.
	ImportSignCertForUpdate(ImportSignCertForUpdate *ImportSignCertForUpdate) (*ImportSignCertForUpdateResponse, error)

	// PriKeyDecryptEx was auto-generated from WSDL.
	PriKeyDecryptEx(PriKeyDecryptEx *PriKeyDecryptEx) (*PriKeyDecryptExResponse, error)

	// PubKeyEncrypt was auto-generated from WSDL.
	PubKeyEncrypt(PubKeyEncrypt *PubKeyEncrypt) (*PubKeyEncryptResponse, error)

	// PubKeyEncryptEx was auto-generated from WSDL.
	PubKeyEncryptEx(PubKeyEncryptEx *PubKeyEncryptEx) (*PubKeyEncryptExResponse, error)

	// SignData was auto-generated from WSDL.
	SignData(SignData *SignData) (*SignDataResponse, error)

	// SignDataByteEx was auto-generated from WSDL.
	SignDataByteEx(SignDataByteEx *SignDataByteEx) (*SignDataByteExResponse, error)

	// SignDataByteEx_raw was auto-generated from WSDL.
	SignDataByteEx_raw(SignDataByteEx_raw *SignDataByteEx_raw) (*SignDataByteEx_rawResponse, error)

	// SignDataEx was auto-generated from WSDL.
	SignDataEx(SignDataEx *SignDataEx) (*SignDataExResponse, error)

	// SignDataP7Detach was auto-generated from WSDL.
	SignDataP7Detach(SignDataP7Detach *SignDataP7Detach) (*SignDataP7DetachResponse, error)

	// Sm3Hash was auto-generated from WSDL.
	Sm3Hash(Sm3Hash *Sm3Hash) (*Sm3HashResponse, error)

	// Sm3HashRaw was auto-generated from WSDL.
	Sm3HashRaw(Sm3HashRaw *Sm3HashRaw) (*Sm3HashRawResponse, error)

	// SymmDataDec was auto-generated from WSDL.
	SymmDataDec(SymmDataDec *SymmDataDec) (*SymmDataDecResponse, error)

	// SymmDataEnc was auto-generated from WSDL.
	SymmDataEnc(SymmDataEnc *SymmDataEnc) (*SymmDataEncResponse, error)

	// SymmDataEncEx was auto-generated from WSDL.
	SymmDataEncEx(SymmDataEncEx *SymmDataEncEx) (*SymmDataEncExResponse, error)

	// VerifyCertAndSignedData was auto-generated from WSDL.
	VerifyCertAndSignedData(VerifyCertAndSignedData *VerifyCertAndSignedData) (*VerifyCertAndSignedDataResponse, error)

	// VerifyDetachSignData was auto-generated from WSDL.
	VerifyDetachSignData(VerifyDetachSignData *VerifyDetachSignData) (*VerifyDetachSignDataResponse, error)

	// VerifyDetachSignDataEx was auto-generated from WSDL.
	VerifyDetachSignDataEx(VerifyDetachSignDataEx *VerifyDetachSignDataEx) (*VerifyDetachSignDataExResponse, error)

	// VerifySignedData was auto-generated from WSDL.
	VerifySignedData(VerifySignedData *VerifySignedData) (*VerifySignedDataResponse, error)

	// VerifySignedDataP1 was auto-generated from WSDL.
	VerifySignedDataP1(VerifySignedDataP1 *VerifySignedDataP1) (*VerifySignedDataP1Response, error)

	// VerifySignedDataP1Byte was auto-generated from WSDL.
	VerifySignedDataP1Byte(VerifySignedDataP1Byte *VerifySignedDataP1Byte) (*VerifySignedDataP1ByteResponse, error)

	// VerifyTimeStamp was auto-generated from WSDL.
	VerifyTimeStamp(VerifyTimeStamp *VerifyTimeStamp) (*VerifyTimeStampResponse, error)
}

// CreateP10 was auto-generated from WSDL.
type CreateP10 struct {
	AppKey     *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret  *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId     *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	CertName   *string `xml:"certName,omitempty" json:"certName,omitempty" yaml:"certName,omitempty"`
	ApplyDn    *string `xml:"applyDn,omitempty" json:"applyDn,omitempty" yaml:"applyDn,omitempty"`
	EncryptAlg *string `xml:"encryptAlg,omitempty" json:"encryptAlg,omitempty" yaml:"encryptAlg,omitempty"`
	KeyLength  *string `xml:"keyLength,omitempty" json:"keyLength,omitempty" yaml:"keyLength,omitempty"`
	DigestAlg  *string `xml:"digestAlg,omitempty" json:"digestAlg,omitempty" yaml:"digestAlg,omitempty"`
}

// CreateP10ForUpdate was auto-generated from WSDL.
type CreateP10ForUpdate struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
}

// CreateP10ForUpdateResponse was auto-generated from WSDL.
type CreateP10ForUpdateResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// CreateP10Response was auto-generated from WSDL.
type CreateP10Response struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// CreateTimeStamp was auto-generated from WSDL.
type CreateTimeStamp struct {
	AppKey           *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret        *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	TimeStampRequest *string `xml:"timeStampRequest,omitempty" json:"timeStampRequest,omitempty" yaml:"timeStampRequest,omitempty"`
}

// CreateTimeStampRequest was auto-generated from WSDL.
type CreateTimeStampRequest struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	Digest    *string `xml:"digest,omitempty" json:"digest,omitempty" yaml:"digest,omitempty"`
}

// CreateTimeStampRequestResponse was auto-generated from WSDL.
type CreateTimeStampRequestResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// CreateTimeStampResponse was auto-generated from WSDL.
type CreateTimeStampResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// DecryptEnvelop was auto-generated from WSDL.
type DecryptEnvelop struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// DecryptEnvelopResponse was auto-generated from WSDL.
type DecryptEnvelopResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// DeleteEncCert was auto-generated from WSDL.
type DeleteEncCert struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
}

// DeleteEncCertResponse was auto-generated from WSDL.
type DeleteEncCertResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// DeleteSignCert was auto-generated from WSDL.
type DeleteSignCert struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
}

// DeleteSignCertResponse was auto-generated from WSDL.
type DeleteSignCertResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// EncryptEnvelop was auto-generated from WSDL.
type EncryptEnvelop struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// EncryptEnvelopResponse was auto-generated from WSDL.
type EncryptEnvelopResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// GenRandom was auto-generated from WSDL.
type GenRandom struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
}

// GenRandomResponse was auto-generated from WSDL.
type GenRandomResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// GetEncCert was auto-generated from WSDL.
type GetEncCert struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
}

// GetEncCertResponse was auto-generated from WSDL.
type GetEncCertResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// GetSealImage was auto-generated from WSDL.
type GetSealImage struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	SealId    *string `xml:"sealId,omitempty" json:"sealId,omitempty" yaml:"sealId,omitempty"`
}

// GetSealImageResponse was auto-generated from WSDL.
type GetSealImageResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// GetServerCert was auto-generated from WSDL.
type GetServerCert struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
}

// GetServerCertEx was auto-generated from WSDL.
type GetServerCertEx struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
}

// GetServerCertExResponse was auto-generated from WSDL.
type GetServerCertExResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// GetServerCertResponse was auto-generated from WSDL.
type GetServerCertResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// GetSignCert was auto-generated from WSDL.
type GetSignCert struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
}

// GetSignCertResponse was auto-generated from WSDL.
type GetSignCertResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// Hello was auto-generated from WSDL.
type Hello struct {
}

// HelloResponse was auto-generated from WSDL.
type HelloResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// ImportEncCert was auto-generated from WSDL.
type ImportEncCert struct {
	AppKey          *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret       *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	RootId          *string `xml:"rootId,omitempty" json:"rootId,omitempty" yaml:"rootId,omitempty"`
	SignCertId      *string `xml:"signCertId,omitempty" json:"signCertId,omitempty" yaml:"signCertId,omitempty"`
	EncCertId       *string `xml:"encCertId,omitempty" json:"encCertId,omitempty" yaml:"encCertId,omitempty"`
	EncCertB64      *string `xml:"encCertB64,omitempty" json:"encCertB64,omitempty" yaml:"encCertB64,omitempty"`
	DoubleEncPriKey *string `xml:"doubleEncPriKey,omitempty" json:"doubleEncPriKey,omitempty" yaml:"doubleEncPriKey,omitempty"`
	CertType        *string `xml:"certType,omitempty" json:"certType,omitempty" yaml:"certType,omitempty"`
}

// ImportEncCertForUpdate was auto-generated from WSDL.
type ImportEncCertForUpdate struct {
	AppKey          *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret       *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	RootId          *string `xml:"rootId,omitempty" json:"rootId,omitempty" yaml:"rootId,omitempty"`
	SignCertId      *string `xml:"signCertId,omitempty" json:"signCertId,omitempty" yaml:"signCertId,omitempty"`
	EncCertId       *string `xml:"encCertId,omitempty" json:"encCertId,omitempty" yaml:"encCertId,omitempty"`
	EncCertB64      *string `xml:"encCertB64,omitempty" json:"encCertB64,omitempty" yaml:"encCertB64,omitempty"`
	DoubleEncPriKey *string `xml:"doubleEncPriKey,omitempty" json:"doubleEncPriKey,omitempty" yaml:"doubleEncPriKey,omitempty"`
	CertType        *string `xml:"certType,omitempty" json:"certType,omitempty" yaml:"certType,omitempty"`
}

// ImportEncCertForUpdateResponse was auto-generated from WSDL.
type ImportEncCertForUpdateResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// ImportEncCertResponse was auto-generated from WSDL.
type ImportEncCertResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// ImportSignCert was auto-generated from WSDL.
type ImportSignCert struct {
	AppKey       *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret    *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId       *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	CertName     *string `xml:"certName,omitempty" json:"certName,omitempty" yaml:"certName,omitempty"`
	SignCertB64  *string `xml:"signCertB64,omitempty" json:"signCertB64,omitempty" yaml:"signCertB64,omitempty"`
	CertType     *string `xml:"certType,omitempty" json:"certType,omitempty" yaml:"certType,omitempty"`
	RootCertName *string `xml:"rootCertName,omitempty" json:"rootCertName,omitempty" yaml:"rootCertName,omitempty"`
	ImportType   *string `xml:"importType,omitempty" json:"importType,omitempty" yaml:"importType,omitempty"`
	Password     *string `xml:"password,omitempty" json:"password,omitempty" yaml:"password,omitempty"`
}

// ImportSignCertForUpdate was auto-generated from WSDL.
type ImportSignCertForUpdate struct {
	AppKey       *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret    *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId       *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	CertName     *string `xml:"certName,omitempty" json:"certName,omitempty" yaml:"certName,omitempty"`
	SignCertB64  *string `xml:"signCertB64,omitempty" json:"signCertB64,omitempty" yaml:"signCertB64,omitempty"`
	CertType     *string `xml:"certType,omitempty" json:"certType,omitempty" yaml:"certType,omitempty"`
	RootCertName *string `xml:"rootCertName,omitempty" json:"rootCertName,omitempty" yaml:"rootCertName,omitempty"`
	ImportType   *string `xml:"importType,omitempty" json:"importType,omitempty" yaml:"importType,omitempty"`
	Password     *string `xml:"password,omitempty" json:"password,omitempty" yaml:"password,omitempty"`
}

// ImportSignCertForUpdateResponse was auto-generated from WSDL.
type ImportSignCertForUpdateResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// ImportSignCertResponse was auto-generated from WSDL.
type ImportSignCertResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// PriKeyDecryptEx was auto-generated from WSDL.
type PriKeyDecryptEx struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	EncCertId *string `xml:"encCertId,omitempty" json:"encCertId,omitempty" yaml:"encCertId,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// PriKeyDecryptExResponse was auto-generated from WSDL.
type PriKeyDecryptExResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// PubKeyEncrypt was auto-generated from WSDL.
type PubKeyEncrypt struct {
	AppKey     *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret  *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	EncCertB64 *string `xml:"encCertB64,omitempty" json:"encCertB64,omitempty" yaml:"encCertB64,omitempty"`
	InData     *[]byte `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// PubKeyEncryptEx was auto-generated from WSDL.
type PubKeyEncryptEx struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	EncCertId *string `xml:"encCertId,omitempty" json:"encCertId,omitempty" yaml:"encCertId,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// PubKeyEncryptExResponse was auto-generated from WSDL.
type PubKeyEncryptExResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// PubKeyEncryptResponse was auto-generated from WSDL.
type PubKeyEncryptResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SignData was auto-generated from WSDL.
type SignData struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// SignDataByteEx was auto-generated from WSDL.
type SignDataByteEx struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	OriData   *[]byte `xml:"oriData,omitempty" json:"oriData,omitempty" yaml:"oriData,omitempty"`
}

// SignDataByteExResponse was auto-generated from WSDL.
type SignDataByteExResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SignDataByteEx_raw was auto-generated from WSDL.
type SignDataByteEx_raw struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	OriData   *[]byte `xml:"oriData,omitempty" json:"oriData,omitempty" yaml:"oriData,omitempty"`
}

// SignDataByteEx_rawResponse was auto-generated from WSDL.
type SignDataByteEx_rawResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SignDataEx was auto-generated from WSDL.
type SignDataEx struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	OriData   *string `xml:"oriData,omitempty" json:"oriData,omitempty" yaml:"oriData,omitempty"`
}

// SignDataExResponse was auto-generated from WSDL.
type SignDataExResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SignDataP7Detach was auto-generated from WSDL.
type SignDataP7Detach struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	CertId    *string `xml:"certId,omitempty" json:"certId,omitempty" yaml:"certId,omitempty"`
	OriData   *string `xml:"oriData,omitempty" json:"oriData,omitempty" yaml:"oriData,omitempty"`
}

// SignDataP7DetachResponse was auto-generated from WSDL.
type SignDataP7DetachResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SignDataResponse was auto-generated from WSDL.
type SignDataResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// Sm3Hash was auto-generated from WSDL.
type Sm3Hash struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
	PubKeyB64 *string `xml:"pubKeyB64,omitempty" json:"pubKeyB64,omitempty" yaml:"pubKeyB64,omitempty"`
}

// Sm3HashRaw was auto-generated from WSDL.
type Sm3HashRaw struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// Sm3HashRawResponse was auto-generated from WSDL.
type Sm3HashRawResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// Sm3HashResponse was auto-generated from WSDL.
type Sm3HashResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SymmDataDec was auto-generated from WSDL.
type SymmDataDec struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	KeyB64    *string `xml:"keyB64,omitempty" json:"keyB64,omitempty" yaml:"keyB64,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// SymmDataDecResponse was auto-generated from WSDL.
type SymmDataDecResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SymmDataEnc was auto-generated from WSDL.
type SymmDataEnc struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	KeyB64    *string `xml:"keyB64,omitempty" json:"keyB64,omitempty" yaml:"keyB64,omitempty"`
	InData    *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// SymmDataEncEx was auto-generated from WSDL.
type SymmDataEncEx struct {
	AppKey    *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	KeyB64    *string `xml:"keyB64,omitempty" json:"keyB64,omitempty" yaml:"keyB64,omitempty"`
	InData    *[]byte `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
}

// SymmDataEncExResponse was auto-generated from WSDL.
type SymmDataEncExResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// SymmDataEncResponse was auto-generated from WSDL.
type SymmDataEncResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// VerifyCertAndSignedData was auto-generated from WSDL.
type VerifyCertAndSignedData struct {
	AppKey     *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret  *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	BstrCert   *string `xml:"bstrCert,omitempty" json:"bstrCert,omitempty" yaml:"bstrCert,omitempty"`
	InData     *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
	SignedData *string `xml:"signedData,omitempty" json:"signedData,omitempty" yaml:"signedData,omitempty"`
}

// VerifyCertAndSignedDataResponse was auto-generated from WSDL.
type VerifyCertAndSignedDataResponse struct {
	Return *int `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// VerifyDetachSignData was auto-generated from WSDL.
type VerifyDetachSignData struct {
	AppKey     *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret  *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	OriData    *string `xml:"oriData,omitempty" json:"oriData,omitempty" yaml:"oriData,omitempty"`
	SignedData *string `xml:"signedData,omitempty" json:"signedData,omitempty" yaml:"signedData,omitempty"`
}

// VerifyDetachSignDataEx was auto-generated from WSDL.
type VerifyDetachSignDataEx struct {
	AppKey       *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret    *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	OriData      *string `xml:"oriData,omitempty" json:"oriData,omitempty" yaml:"oriData,omitempty"`
	SignedData   *string `xml:"signedData,omitempty" json:"signedData,omitempty" yaml:"signedData,omitempty"`
	IsCheckCert  *bool   `xml:"isCheckCert,omitempty" json:"isCheckCert,omitempty" yaml:"isCheckCert,omitempty"`
	IsCheckCrl   *bool   `xml:"isCheckCrl,omitempty" json:"isCheckCrl,omitempty" yaml:"isCheckCrl,omitempty"`
	IsCheckChain *bool   `xml:"isCheckChain,omitempty" json:"isCheckChain,omitempty" yaml:"isCheckChain,omitempty"`
}

// VerifyDetachSignDataExResponse was auto-generated from WSDL.
type VerifyDetachSignDataExResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// VerifyDetachSignDataResponse was auto-generated from WSDL.
type VerifyDetachSignDataResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// VerifySignedData was auto-generated from WSDL.
type VerifySignedData struct {
	AppKey     *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret  *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	BstrCert   *string `xml:"bstrCert,omitempty" json:"bstrCert,omitempty" yaml:"bstrCert,omitempty"`
	InData     *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
	SignedData *string `xml:"signedData,omitempty" json:"signedData,omitempty" yaml:"signedData,omitempty"`
}

// VerifySignedDataP1 was auto-generated from WSDL.
type VerifySignedDataP1 struct {
	AppKey     *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret  *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	BstrCert   *string `xml:"bstrCert,omitempty" json:"bstrCert,omitempty" yaml:"bstrCert,omitempty"`
	InData     *string `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
	SignedData *string `xml:"signedData,omitempty" json:"signedData,omitempty" yaml:"signedData,omitempty"`
}

// VerifySignedDataP1Byte was auto-generated from WSDL.
type VerifySignedDataP1Byte struct {
	AppKey     *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret  *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	BstrCert   *string `xml:"bstrCert,omitempty" json:"bstrCert,omitempty" yaml:"bstrCert,omitempty"`
	InData     *[]byte `xml:"inData,omitempty" json:"inData,omitempty" yaml:"inData,omitempty"`
	SignedData *string `xml:"signedData,omitempty" json:"signedData,omitempty" yaml:"signedData,omitempty"`
}

// VerifySignedDataP1ByteResponse was auto-generated from WSDL.
type VerifySignedDataP1ByteResponse struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// VerifySignedDataP1Response was auto-generated from WSDL.
type VerifySignedDataP1Response struct {
	Return *string `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// VerifySignedDataResponse was auto-generated from WSDL.
type VerifySignedDataResponse struct {
	Return *int `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// VerifyTimeStamp was auto-generated from WSDL.
type VerifyTimeStamp struct {
	AppKey          *string `xml:"appKey,omitempty" json:"appKey,omitempty" yaml:"appKey,omitempty"`
	AppSecret       *string `xml:"appSecret,omitempty" json:"appSecret,omitempty" yaml:"appSecret,omitempty"`
	TimeStampString *string `xml:"timeStampString,omitempty" json:"timeStampString,omitempty" yaml:"timeStampString,omitempty"`
}

// VerifyTimeStampResponse was auto-generated from WSDL.
type VerifyTimeStampResponse struct {
	Return *int `xml:"return,omitempty" json:"return,omitempty" yaml:"return,omitempty"`
}

// Operation wrapper for CreateP10.
// OperationCreateP10 was auto-generated from WSDL.
type OperationCreateP10 struct {
	CreateP10 *CreateP10 `xml:"tns:createP10,omitempty" json:"createP10,omitempty" yaml:"createP10,omitempty"`
}

// Operation wrapper for CreateP10.
// OperationCreateP10Response was auto-generated from WSDL.
type OperationCreateP10Response struct {
	CreateP10Response *CreateP10Response `xml:"createP10Response,omitempty" json:"createP10Response,omitempty" yaml:"createP10Response,omitempty"`
}

// Operation wrapper for CreateP10ForUpdate.
// OperationCreateP10ForUpdate was auto-generated from WSDL.
type OperationCreateP10ForUpdate struct {
	CreateP10ForUpdate *CreateP10ForUpdate `xml:"tns:createP10ForUpdate,omitempty" json:"createP10ForUpdate,omitempty" yaml:"createP10ForUpdate,omitempty"`
}

// Operation wrapper for CreateP10ForUpdate.
// OperationCreateP10ForUpdateResponse was auto-generated from
// WSDL.
type OperationCreateP10ForUpdateResponse struct {
	CreateP10ForUpdateResponse *CreateP10ForUpdateResponse `xml:"createP10ForUpdateResponse,omitempty" json:"createP10ForUpdateResponse,omitempty" yaml:"createP10ForUpdateResponse,omitempty"`
}

// Operation wrapper for CreateTimeStamp.
// OperationCreateTimeStamp was auto-generated from WSDL.
type OperationCreateTimeStamp struct {
	CreateTimeStamp *CreateTimeStamp `xml:"tns:createTimeStamp,omitempty" json:"createTimeStamp,omitempty" yaml:"createTimeStamp,omitempty"`
}

// Operation wrapper for CreateTimeStamp.
// OperationCreateTimeStampResponse was auto-generated from WSDL.
type OperationCreateTimeStampResponse struct {
	CreateTimeStampResponse *CreateTimeStampResponse `xml:"createTimeStampResponse,omitempty" json:"createTimeStampResponse,omitempty" yaml:"createTimeStampResponse,omitempty"`
}

// Operation wrapper for CreateTimeStampRequest.
// OperationCreateTimeStampRequest was auto-generated from WSDL.
type OperationCreateTimeStampRequest struct {
	CreateTimeStampRequest *CreateTimeStampRequest `xml:"tns:createTimeStampRequest,omitempty" json:"createTimeStampRequest,omitempty" yaml:"createTimeStampRequest,omitempty"`
}

// Operation wrapper for CreateTimeStampRequest.
// OperationCreateTimeStampRequestResponse was auto-generated from
// WSDL.
type OperationCreateTimeStampRequestResponse struct {
	CreateTimeStampRequestResponse *CreateTimeStampRequestResponse `xml:"createTimeStampRequestResponse,omitempty" json:"createTimeStampRequestResponse,omitempty" yaml:"createTimeStampRequestResponse,omitempty"`
}

// Operation wrapper for DecryptEnvelop.
// OperationDecryptEnvelop was auto-generated from WSDL.
type OperationDecryptEnvelop struct {
	DecryptEnvelop *DecryptEnvelop `xml:"tns:decryptEnvelop,omitempty" json:"decryptEnvelop,omitempty" yaml:"decryptEnvelop,omitempty"`
}

// Operation wrapper for DecryptEnvelop.
// OperationDecryptEnvelopResponse was auto-generated from WSDL.
type OperationDecryptEnvelopResponse struct {
	DecryptEnvelopResponse *DecryptEnvelopResponse `xml:"decryptEnvelopResponse,omitempty" json:"decryptEnvelopResponse,omitempty" yaml:"decryptEnvelopResponse,omitempty"`
}

// Operation wrapper for DeleteEncCert.
// OperationDeleteEncCert was auto-generated from WSDL.
type OperationDeleteEncCert struct {
	DeleteEncCert *DeleteEncCert `xml:"tns:deleteEncCert,omitempty" json:"deleteEncCert,omitempty" yaml:"deleteEncCert,omitempty"`
}

// Operation wrapper for DeleteEncCert.
// OperationDeleteEncCertResponse was auto-generated from WSDL.
type OperationDeleteEncCertResponse struct {
	DeleteEncCertResponse *DeleteEncCertResponse `xml:"deleteEncCertResponse,omitempty" json:"deleteEncCertResponse,omitempty" yaml:"deleteEncCertResponse,omitempty"`
}

// Operation wrapper for DeleteSignCert.
// OperationDeleteSignCert was auto-generated from WSDL.
type OperationDeleteSignCert struct {
	DeleteSignCert *DeleteSignCert `xml:"tns:deleteSignCert,omitempty" json:"deleteSignCert,omitempty" yaml:"deleteSignCert,omitempty"`
}

// Operation wrapper for DeleteSignCert.
// OperationDeleteSignCertResponse was auto-generated from WSDL.
type OperationDeleteSignCertResponse struct {
	DeleteSignCertResponse *DeleteSignCertResponse `xml:"deleteSignCertResponse,omitempty" json:"deleteSignCertResponse,omitempty" yaml:"deleteSignCertResponse,omitempty"`
}

// Operation wrapper for EncryptEnvelop.
// OperationEncryptEnvelop was auto-generated from WSDL.
type OperationEncryptEnvelop struct {
	EncryptEnvelop *EncryptEnvelop `xml:"tns:encryptEnvelop,omitempty" json:"encryptEnvelop,omitempty" yaml:"encryptEnvelop,omitempty"`
}

// Operation wrapper for EncryptEnvelop.
// OperationEncryptEnvelopResponse was auto-generated from WSDL.
type OperationEncryptEnvelopResponse struct {
	EncryptEnvelopResponse *EncryptEnvelopResponse `xml:"encryptEnvelopResponse,omitempty" json:"encryptEnvelopResponse,omitempty" yaml:"encryptEnvelopResponse,omitempty"`
}

// Operation wrapper for GenRandom.
// OperationGenRandom was auto-generated from WSDL.
type OperationGenRandom struct {
	GenRandom *GenRandom `xml:"tns:genRandom,omitempty" json:"genRandom,omitempty" yaml:"genRandom,omitempty"`
}

// Operation wrapper for GenRandom.
// OperationGenRandomResponse was auto-generated from WSDL.
type OperationGenRandomResponse struct {
	GenRandomResponse *GenRandomResponse `xml:"genRandomResponse,omitempty" json:"genRandomResponse,omitempty" yaml:"genRandomResponse,omitempty"`
}

// Operation wrapper for GetEncCert.
// OperationGetEncCert was auto-generated from WSDL.
type OperationGetEncCert struct {
	GetEncCert *GetEncCert `xml:"tns:getEncCert,omitempty" json:"getEncCert,omitempty" yaml:"getEncCert,omitempty"`
}

// Operation wrapper for GetEncCert.
// OperationGetEncCertResponse was auto-generated from WSDL.
type OperationGetEncCertResponse struct {
	GetEncCertResponse *GetEncCertResponse `xml:"getEncCertResponse,omitempty" json:"getEncCertResponse,omitempty" yaml:"getEncCertResponse,omitempty"`
}

// Operation wrapper for GetSealImage.
// OperationGetSealImage was auto-generated from WSDL.
type OperationGetSealImage struct {
	GetSealImage *GetSealImage `xml:"tns:getSealImage,omitempty" json:"getSealImage,omitempty" yaml:"getSealImage,omitempty"`
}

// Operation wrapper for GetSealImage.
// OperationGetSealImageResponse was auto-generated from WSDL.
type OperationGetSealImageResponse struct {
	GetSealImageResponse *GetSealImageResponse `xml:"getSealImageResponse,omitempty" json:"getSealImageResponse,omitempty" yaml:"getSealImageResponse,omitempty"`
}

// Operation wrapper for GetServerCert.
// OperationGetServerCert was auto-generated from WSDL.
type OperationGetServerCert struct {
	GetServerCert *GetServerCert `xml:"tns:getServerCert,omitempty" json:"getServerCert,omitempty" yaml:"getServerCert,omitempty"`
}

// Operation wrapper for GetServerCert.
// OperationGetServerCertResponse was auto-generated from WSDL.
type OperationGetServerCertResponse struct {
	GetServerCertResponse *GetServerCertResponse `xml:"getServerCertResponse,omitempty" json:"getServerCertResponse,omitempty" yaml:"getServerCertResponse,omitempty"`
}

// Operation wrapper for GetServerCertEx.
// OperationGetServerCertEx was auto-generated from WSDL.
type OperationGetServerCertEx struct {
	GetServerCertEx *GetServerCertEx `xml:"tns:getServerCertEx,omitempty" json:"getServerCertEx,omitempty" yaml:"getServerCertEx,omitempty"`
}

// Operation wrapper for GetServerCertEx.
// OperationGetServerCertExResponse was auto-generated from WSDL.
type OperationGetServerCertExResponse struct {
	GetServerCertExResponse *GetServerCertExResponse `xml:"getServerCertExResponse,omitempty" json:"getServerCertExResponse,omitempty" yaml:"getServerCertExResponse,omitempty"`
}

// Operation wrapper for GetSignCert.
// OperationGetSignCert was auto-generated from WSDL.
type OperationGetSignCert struct {
	GetSignCert *GetSignCert `xml:"tns:getSignCert,omitempty" json:"getSignCert,omitempty" yaml:"getSignCert,omitempty"`
}

// Operation wrapper for GetSignCert.
// OperationGetSignCertResponse was auto-generated from WSDL.
type OperationGetSignCertResponse struct {
	GetSignCertResponse *GetSignCertResponse `xml:"getSignCertResponse,omitempty" json:"getSignCertResponse,omitempty" yaml:"getSignCertResponse,omitempty"`
}

// Operation wrapper for Hello.
// OperationHello was auto-generated from WSDL.
type OperationHello struct {
	Hello *Hello `xml:"tns:hello,omitempty" json:"hello,omitempty" yaml:"hello,omitempty"`
}

// Operation wrapper for Hello.
// OperationHelloResponse was auto-generated from WSDL.
type OperationHelloResponse struct {
	HelloResponse *HelloResponse `xml:"helloResponse,omitempty" json:"helloResponse,omitempty" yaml:"helloResponse,omitempty"`
}

// Operation wrapper for ImportEncCert.
// OperationImportEncCert was auto-generated from WSDL.
type OperationImportEncCert struct {
	ImportEncCert *ImportEncCert `xml:"tns:importEncCert,omitempty" json:"importEncCert,omitempty" yaml:"importEncCert,omitempty"`
}

// Operation wrapper for ImportEncCert.
// OperationImportEncCertResponse was auto-generated from WSDL.
type OperationImportEncCertResponse struct {
	ImportEncCertResponse *ImportEncCertResponse `xml:"importEncCertResponse,omitempty" json:"importEncCertResponse,omitempty" yaml:"importEncCertResponse,omitempty"`
}

// Operation wrapper for ImportEncCertForUpdate.
// OperationImportEncCertForUpdate was auto-generated from WSDL.
type OperationImportEncCertForUpdate struct {
	ImportEncCertForUpdate *ImportEncCertForUpdate `xml:"tns:importEncCertForUpdate,omitempty" json:"importEncCertForUpdate,omitempty" yaml:"importEncCertForUpdate,omitempty"`
}

// Operation wrapper for ImportEncCertForUpdate.
// OperationImportEncCertForUpdateResponse was auto-generated from
// WSDL.
type OperationImportEncCertForUpdateResponse struct {
	ImportEncCertForUpdateResponse *ImportEncCertForUpdateResponse `xml:"importEncCertForUpdateResponse,omitempty" json:"importEncCertForUpdateResponse,omitempty" yaml:"importEncCertForUpdateResponse,omitempty"`
}

// Operation wrapper for ImportSignCert.
// OperationImportSignCert was auto-generated from WSDL.
type OperationImportSignCert struct {
	ImportSignCert *ImportSignCert `xml:"tns:importSignCert,omitempty" json:"importSignCert,omitempty" yaml:"importSignCert,omitempty"`
}

// Operation wrapper for ImportSignCert.
// OperationImportSignCertResponse was auto-generated from WSDL.
type OperationImportSignCertResponse struct {
	ImportSignCertResponse *ImportSignCertResponse `xml:"importSignCertResponse,omitempty" json:"importSignCertResponse,omitempty" yaml:"importSignCertResponse,omitempty"`
}

// Operation wrapper for ImportSignCertForUpdate.
// OperationImportSignCertForUpdate was auto-generated from WSDL.
type OperationImportSignCertForUpdate struct {
	ImportSignCertForUpdate *ImportSignCertForUpdate `xml:"tns:importSignCertForUpdate,omitempty" json:"importSignCertForUpdate,omitempty" yaml:"importSignCertForUpdate,omitempty"`
}

// Operation wrapper for ImportSignCertForUpdate.
// OperationImportSignCertForUpdateResponse was auto-generated
// from WSDL.
type OperationImportSignCertForUpdateResponse struct {
	ImportSignCertForUpdateResponse *ImportSignCertForUpdateResponse `xml:"importSignCertForUpdateResponse,omitempty" json:"importSignCertForUpdateResponse,omitempty" yaml:"importSignCertForUpdateResponse,omitempty"`
}

// Operation wrapper for PriKeyDecryptEx.
// OperationPriKeyDecryptEx was auto-generated from WSDL.
type OperationPriKeyDecryptEx struct {
	PriKeyDecryptEx *PriKeyDecryptEx `xml:"tns:priKeyDecryptEx,omitempty" json:"priKeyDecryptEx,omitempty" yaml:"priKeyDecryptEx,omitempty"`
}

// Operation wrapper for PriKeyDecryptEx.
// OperationPriKeyDecryptExResponse was auto-generated from WSDL.
type OperationPriKeyDecryptExResponse struct {
	PriKeyDecryptExResponse *PriKeyDecryptExResponse `xml:"priKeyDecryptExResponse,omitempty" json:"priKeyDecryptExResponse,omitempty" yaml:"priKeyDecryptExResponse,omitempty"`
}

// Operation wrapper for PubKeyEncrypt.
// OperationPubKeyEncrypt was auto-generated from WSDL.
type OperationPubKeyEncrypt struct {
	PubKeyEncrypt *PubKeyEncrypt `xml:"tns:pubKeyEncrypt,omitempty" json:"pubKeyEncrypt,omitempty" yaml:"pubKeyEncrypt,omitempty"`
}

// Operation wrapper for PubKeyEncrypt.
// OperationPubKeyEncryptResponse was auto-generated from WSDL.
type OperationPubKeyEncryptResponse struct {
	PubKeyEncryptResponse *PubKeyEncryptResponse `xml:"pubKeyEncryptResponse,omitempty" json:"pubKeyEncryptResponse,omitempty" yaml:"pubKeyEncryptResponse,omitempty"`
}

// Operation wrapper for PubKeyEncryptEx.
// OperationPubKeyEncryptEx was auto-generated from WSDL.
type OperationPubKeyEncryptEx struct {
	PubKeyEncryptEx *PubKeyEncryptEx `xml:"tns:pubKeyEncryptEx,omitempty" json:"pubKeyEncryptEx,omitempty" yaml:"pubKeyEncryptEx,omitempty"`
}

// Operation wrapper for PubKeyEncryptEx.
// OperationPubKeyEncryptExResponse was auto-generated from WSDL.
type OperationPubKeyEncryptExResponse struct {
	PubKeyEncryptExResponse *PubKeyEncryptExResponse `xml:"pubKeyEncryptExResponse,omitempty" json:"pubKeyEncryptExResponse,omitempty" yaml:"pubKeyEncryptExResponse,omitempty"`
}

// Operation wrapper for SignData.
// OperationSignData was auto-generated from WSDL.
type OperationSignData struct {
	SignData *SignData `xml:"tns:signData,omitempty" json:"signData,omitempty" yaml:"signData,omitempty"`
}

// Operation wrapper for SignData.
// OperationSignDataResponse was auto-generated from WSDL.
type OperationSignDataResponse struct {
	SignDataResponse *SignDataResponse `xml:"signDataResponse,omitempty" json:"signDataResponse,omitempty" yaml:"signDataResponse,omitempty"`
}

// Operation wrapper for SignDataByteEx.
// OperationSignDataByteEx was auto-generated from WSDL.
type OperationSignDataByteEx struct {
	SignDataByteEx *SignDataByteEx `xml:"tns:signDataByteEx,omitempty" json:"signDataByteEx,omitempty" yaml:"signDataByteEx,omitempty"`
}

// Operation wrapper for SignDataByteEx.
// OperationSignDataByteExResponse was auto-generated from WSDL.
type OperationSignDataByteExResponse struct {
	SignDataByteExResponse *SignDataByteExResponse `xml:"signDataByteExResponse,omitempty" json:"signDataByteExResponse,omitempty" yaml:"signDataByteExResponse,omitempty"`
}

// Operation wrapper for SignDataByteEx_raw.
// OperationSignDataByteEx_raw was auto-generated from WSDL.
type OperationSignDataByteEx_raw struct {
	SignDataByteEx_raw *SignDataByteEx_raw `xml:"tns:signDataByteEx_raw,omitempty" json:"signDataByteEx_raw,omitempty" yaml:"signDataByteEx_raw,omitempty"`
}

// Operation wrapper for SignDataByteEx_raw.
// OperationSignDataByteEx_rawResponse was auto-generated from
// WSDL.
type OperationSignDataByteEx_rawResponse struct {
	SignDataByteEx_rawResponse *SignDataByteEx_rawResponse `xml:"signDataByteEx_rawResponse,omitempty" json:"signDataByteEx_rawResponse,omitempty" yaml:"signDataByteEx_rawResponse,omitempty"`
}

// Operation wrapper for SignDataEx.
// OperationSignDataEx was auto-generated from WSDL.
type OperationSignDataEx struct {
	SignDataEx *SignDataEx `xml:"tns:signDataEx,omitempty" json:"signDataEx,omitempty" yaml:"signDataEx,omitempty"`
}

// Operation wrapper for SignDataEx.
// OperationSignDataExResponse was auto-generated from WSDL.
type OperationSignDataExResponse struct {
	SignDataExResponse *SignDataExResponse `xml:"signDataExResponse,omitempty" json:"signDataExResponse,omitempty" yaml:"signDataExResponse,omitempty"`
}

// Operation wrapper for SignDataP7Detach.
// OperationSignDataP7Detach was auto-generated from WSDL.
type OperationSignDataP7Detach struct {
	SignDataP7Detach *SignDataP7Detach `xml:"tns:signDataP7Detach,omitempty" json:"signDataP7Detach,omitempty" yaml:"signDataP7Detach,omitempty"`
}

// Operation wrapper for SignDataP7Detach.
// OperationSignDataP7DetachResponse was auto-generated from WSDL.
type OperationSignDataP7DetachResponse struct {
	SignDataP7DetachResponse *SignDataP7DetachResponse `xml:"signDataP7DetachResponse,omitempty" json:"signDataP7DetachResponse,omitempty" yaml:"signDataP7DetachResponse,omitempty"`
}

// Operation wrapper for Sm3Hash.
// OperationSm3Hash was auto-generated from WSDL.
type OperationSm3Hash struct {
	Sm3Hash *Sm3Hash `xml:"tns:sm3Hash,omitempty" json:"sm3Hash,omitempty" yaml:"sm3Hash,omitempty"`
}

// Operation wrapper for Sm3Hash.
// OperationSm3HashResponse was auto-generated from WSDL.
type OperationSm3HashResponse struct {
	Sm3HashResponse *Sm3HashResponse `xml:"sm3HashResponse,omitempty" json:"sm3HashResponse,omitempty" yaml:"sm3HashResponse,omitempty"`
}

// Operation wrapper for Sm3HashRaw.
// OperationSm3HashRaw was auto-generated from WSDL.
type OperationSm3HashRaw struct {
	Sm3HashRaw *Sm3HashRaw `xml:"tns:sm3HashRaw,omitempty" json:"sm3HashRaw,omitempty" yaml:"sm3HashRaw,omitempty"`
}

// Operation wrapper for Sm3HashRaw.
// OperationSm3HashRawResponse was auto-generated from WSDL.
type OperationSm3HashRawResponse struct {
	Sm3HashRawResponse *Sm3HashRawResponse `xml:"sm3HashRawResponse,omitempty" json:"sm3HashRawResponse,omitempty" yaml:"sm3HashRawResponse,omitempty"`
}

// Operation wrapper for SymmDataDec.
// OperationSymmDataDec was auto-generated from WSDL.
type OperationSymmDataDec struct {
	SymmDataDec *SymmDataDec `xml:"tns:symmDataDec,omitempty" json:"symmDataDec,omitempty" yaml:"symmDataDec,omitempty"`
}

// Operation wrapper for SymmDataDec.
// OperationSymmDataDecResponse was auto-generated from WSDL.
type OperationSymmDataDecResponse struct {
	SymmDataDecResponse *SymmDataDecResponse `xml:"symmDataDecResponse,omitempty" json:"symmDataDecResponse,omitempty" yaml:"symmDataDecResponse,omitempty"`
}

// Operation wrapper for SymmDataEnc.
// OperationSymmDataEnc was auto-generated from WSDL.
type OperationSymmDataEnc struct {
	SymmDataEnc *SymmDataEnc `xml:"tns:symmDataEnc,omitempty" json:"symmDataEnc,omitempty" yaml:"symmDataEnc,omitempty"`
}

// Operation wrapper for SymmDataEnc.
// OperationSymmDataEncResponse was auto-generated from WSDL.
type OperationSymmDataEncResponse struct {
	SymmDataEncResponse *SymmDataEncResponse `xml:"symmDataEncResponse,omitempty" json:"symmDataEncResponse,omitempty" yaml:"symmDataEncResponse,omitempty"`
}

// Operation wrapper for SymmDataEncEx.
// OperationSymmDataEncEx was auto-generated from WSDL.
type OperationSymmDataEncEx struct {
	SymmDataEncEx *SymmDataEncEx `xml:"tns:symmDataEncEx,omitempty" json:"symmDataEncEx,omitempty" yaml:"symmDataEncEx,omitempty"`
}

// Operation wrapper for SymmDataEncEx.
// OperationSymmDataEncExResponse was auto-generated from WSDL.
type OperationSymmDataEncExResponse struct {
	SymmDataEncExResponse *SymmDataEncExResponse `xml:"symmDataEncExResponse,omitempty" json:"symmDataEncExResponse,omitempty" yaml:"symmDataEncExResponse,omitempty"`
}

// Operation wrapper for VerifyCertAndSignedData.
// OperationVerifyCertAndSignedData was auto-generated from WSDL.
type OperationVerifyCertAndSignedData struct {
	VerifyCertAndSignedData *VerifyCertAndSignedData `xml:"tns:verifyCertAndSignedData,omitempty" json:"verifyCertAndSignedData,omitempty" yaml:"verifyCertAndSignedData,omitempty"`
}

// Operation wrapper for VerifyCertAndSignedData.
// OperationVerifyCertAndSignedDataResponse was auto-generated
// from WSDL.
type OperationVerifyCertAndSignedDataResponse struct {
	VerifyCertAndSignedDataResponse *VerifyCertAndSignedDataResponse `xml:"verifyCertAndSignedDataResponse,omitempty" json:"verifyCertAndSignedDataResponse,omitempty" yaml:"verifyCertAndSignedDataResponse,omitempty"`
}

// Operation wrapper for VerifyDetachSignData.
// OperationVerifyDetachSignData was auto-generated from WSDL.
type OperationVerifyDetachSignData struct {
	VerifyDetachSignData *VerifyDetachSignData `xml:"tns:verifyDetachSignData,omitempty" json:"verifyDetachSignData,omitempty" yaml:"verifyDetachSignData,omitempty"`
}

// Operation wrapper for VerifyDetachSignData.
// OperationVerifyDetachSignDataResponse was auto-generated from
// WSDL.
type OperationVerifyDetachSignDataResponse struct {
	VerifyDetachSignDataResponse *VerifyDetachSignDataResponse `xml:"verifyDetachSignDataResponse,omitempty" json:"verifyDetachSignDataResponse,omitempty" yaml:"verifyDetachSignDataResponse,omitempty"`
}

// Operation wrapper for VerifyDetachSignDataEx.
// OperationVerifyDetachSignDataEx was auto-generated from WSDL.
type OperationVerifyDetachSignDataEx struct {
	VerifyDetachSignDataEx *VerifyDetachSignDataEx `xml:"tns:verifyDetachSignDataEx,omitempty" json:"verifyDetachSignDataEx,omitempty" yaml:"verifyDetachSignDataEx,omitempty"`
}

// Operation wrapper for VerifyDetachSignDataEx.
// OperationVerifyDetachSignDataExResponse was auto-generated from
// WSDL.
type OperationVerifyDetachSignDataExResponse struct {
	VerifyDetachSignDataExResponse *VerifyDetachSignDataExResponse `xml:"verifyDetachSignDataExResponse,omitempty" json:"verifyDetachSignDataExResponse,omitempty" yaml:"verifyDetachSignDataExResponse,omitempty"`
}

// Operation wrapper for VerifySignedData.
// OperationVerifySignedData was auto-generated from WSDL.
type OperationVerifySignedData struct {
	VerifySignedData *VerifySignedData `xml:"tns:verifySignedData,omitempty" json:"verifySignedData,omitempty" yaml:"verifySignedData,omitempty"`
}

// Operation wrapper for VerifySignedData.
// OperationVerifySignedDataResponse was auto-generated from WSDL.
type OperationVerifySignedDataResponse struct {
	VerifySignedDataResponse *VerifySignedDataResponse `xml:"verifySignedDataResponse,omitempty" json:"verifySignedDataResponse,omitempty" yaml:"verifySignedDataResponse,omitempty"`
}

// Operation wrapper for VerifySignedDataP1.
// OperationVerifySignedDataP1 was auto-generated from WSDL.
type OperationVerifySignedDataP1 struct {
	VerifySignedDataP1 *VerifySignedDataP1 `xml:"tns:verifySignedDataP1,omitempty" json:"verifySignedDataP1,omitempty" yaml:"verifySignedDataP1,omitempty"`
}

// Operation wrapper for VerifySignedDataP1.
// OperationVerifySignedDataP1Response was auto-generated from
// WSDL.
type OperationVerifySignedDataP1Response struct {
	VerifySignedDataP1Response *VerifySignedDataP1Response `xml:"verifySignedDataP1Response,omitempty" json:"verifySignedDataP1Response,omitempty" yaml:"verifySignedDataP1Response,omitempty"`
}

// Operation wrapper for VerifySignedDataP1Byte.
// OperationVerifySignedDataP1Byte was auto-generated from WSDL.
type OperationVerifySignedDataP1Byte struct {
	VerifySignedDataP1Byte *VerifySignedDataP1Byte `xml:"tns:verifySignedDataP1Byte,omitempty" json:"verifySignedDataP1Byte,omitempty" yaml:"verifySignedDataP1Byte,omitempty"`
}

// Operation wrapper for VerifySignedDataP1Byte.
// OperationVerifySignedDataP1ByteResponse was auto-generated from
// WSDL.
type OperationVerifySignedDataP1ByteResponse struct {
	VerifySignedDataP1ByteResponse *VerifySignedDataP1ByteResponse `xml:"verifySignedDataP1ByteResponse,omitempty" json:"verifySignedDataP1ByteResponse,omitempty" yaml:"verifySignedDataP1ByteResponse,omitempty"`
}

// Operation wrapper for VerifyTimeStamp.
// OperationVerifyTimeStamp was auto-generated from WSDL.
type OperationVerifyTimeStamp struct {
	VerifyTimeStamp *VerifyTimeStamp `xml:"tns:verifyTimeStamp,omitempty" json:"verifyTimeStamp,omitempty" yaml:"verifyTimeStamp,omitempty"`
}

// Operation wrapper for VerifyTimeStamp.
// OperationVerifyTimeStampResponse was auto-generated from WSDL.
type OperationVerifyTimeStampResponse struct {
	VerifyTimeStampResponse *VerifyTimeStampResponse `xml:"verifyTimeStampResponse,omitempty" json:"verifyTimeStampResponse,omitempty" yaml:"verifyTimeStampResponse,omitempty"`
}

// hbcaService implements the HbcaService interface.
type hbcaService struct {
	cli *soap.Client
}

// CreateP10 was auto-generated from WSDL.
func (p *hbcaService) CreateP10(CreateP10 *CreateP10) (*CreateP10Response, error) {
	α := struct {
		OperationCreateP10 `xml:"tns:createP10"`
	}{
		OperationCreateP10{
			CreateP10,
		},
	}

	γ := struct {
		OperationCreateP10Response `xml:"createP10Response"`
	}{}
	if err := p.cli.RoundTripWithAction("CreateP10", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateP10Response, nil
}

// CreateP10ForUpdate was auto-generated from WSDL.
func (p *hbcaService) CreateP10ForUpdate(CreateP10ForUpdate *CreateP10ForUpdate) (*CreateP10ForUpdateResponse, error) {
	α := struct {
		OperationCreateP10ForUpdate `xml:"tns:createP10ForUpdate"`
	}{
		OperationCreateP10ForUpdate{
			CreateP10ForUpdate,
		},
	}

	γ := struct {
		OperationCreateP10ForUpdateResponse `xml:"createP10ForUpdateResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CreateP10ForUpdate", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateP10ForUpdateResponse, nil
}

// CreateTimeStamp was auto-generated from WSDL.
func (p *hbcaService) CreateTimeStamp(CreateTimeStamp *CreateTimeStamp) (*CreateTimeStampResponse, error) {
	α := struct {
		OperationCreateTimeStamp `xml:"tns:createTimeStamp"`
	}{
		OperationCreateTimeStamp{
			CreateTimeStamp,
		},
	}

	γ := struct {
		OperationCreateTimeStampResponse `xml:"createTimeStampResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CreateTimeStamp", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateTimeStampResponse, nil
}

// CreateTimeStampRequest was auto-generated from WSDL.
func (p *hbcaService) CreateTimeStampRequest(CreateTimeStampRequest *CreateTimeStampRequest) (*CreateTimeStampRequestResponse, error) {
	α := struct {
		OperationCreateTimeStampRequest `xml:"tns:createTimeStampRequest"`
	}{
		OperationCreateTimeStampRequest{
			CreateTimeStampRequest,
		},
	}

	γ := struct {
		OperationCreateTimeStampRequestResponse `xml:"createTimeStampRequestResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("CreateTimeStampRequest", α, &γ); err != nil {
		return nil, err
	}
	return γ.CreateTimeStampRequestResponse, nil
}

// DecryptEnvelop was auto-generated from WSDL.
func (p *hbcaService) DecryptEnvelop(DecryptEnvelop *DecryptEnvelop) (*DecryptEnvelopResponse, error) {
	α := struct {
		OperationDecryptEnvelop `xml:"tns:decryptEnvelop"`
	}{
		OperationDecryptEnvelop{
			DecryptEnvelop,
		},
	}

	γ := struct {
		OperationDecryptEnvelopResponse `xml:"decryptEnvelopResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("DecryptEnvelop", α, &γ); err != nil {
		return nil, err
	}
	return γ.DecryptEnvelopResponse, nil
}

// DeleteEncCert was auto-generated from WSDL.
func (p *hbcaService) DeleteEncCert(DeleteEncCert *DeleteEncCert) (*DeleteEncCertResponse, error) {
	α := struct {
		OperationDeleteEncCert `xml:"tns:deleteEncCert"`
	}{
		OperationDeleteEncCert{
			DeleteEncCert,
		},
	}

	γ := struct {
		OperationDeleteEncCertResponse `xml:"deleteEncCertResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("DeleteEncCert", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteEncCertResponse, nil
}

// DeleteSignCert was auto-generated from WSDL.
func (p *hbcaService) DeleteSignCert(DeleteSignCert *DeleteSignCert) (*DeleteSignCertResponse, error) {
	α := struct {
		OperationDeleteSignCert `xml:"tns:deleteSignCert"`
	}{
		OperationDeleteSignCert{
			DeleteSignCert,
		},
	}

	γ := struct {
		OperationDeleteSignCertResponse `xml:"deleteSignCertResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("DeleteSignCert", α, &γ); err != nil {
		return nil, err
	}
	return γ.DeleteSignCertResponse, nil
}

// EncryptEnvelop was auto-generated from WSDL.
func (p *hbcaService) EncryptEnvelop(EncryptEnvelop *EncryptEnvelop) (*EncryptEnvelopResponse, error) {
	α := struct {
		OperationEncryptEnvelop `xml:"tns:encryptEnvelop"`
	}{
		OperationEncryptEnvelop{
			EncryptEnvelop,
		},
	}

	γ := struct {
		OperationEncryptEnvelopResponse `xml:"encryptEnvelopResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("EncryptEnvelop", α, &γ); err != nil {
		return nil, err
	}
	return γ.EncryptEnvelopResponse, nil
}

// GenRandom was auto-generated from WSDL.
func (p *hbcaService) GenRandom(GenRandom *GenRandom) (*GenRandomResponse, error) {
	α := struct {
		OperationGenRandom `xml:"tns:genRandom"`
	}{
		OperationGenRandom{
			GenRandom,
		},
	}

	γ := struct {
		OperationGenRandomResponse `xml:"genRandomResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("GenRandom", α, &γ); err != nil {
		return nil, err
	}
	return γ.GenRandomResponse, nil
}

// GetEncCert was auto-generated from WSDL.
func (p *hbcaService) GetEncCert(GetEncCert *GetEncCert) (*GetEncCertResponse, error) {
	α := struct {
		OperationGetEncCert `xml:"tns:getEncCert"`
	}{
		OperationGetEncCert{
			GetEncCert,
		},
	}

	γ := struct {
		OperationGetEncCertResponse `xml:"getEncCertResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("GetEncCert", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetEncCertResponse, nil
}

// GetSealImage was auto-generated from WSDL.
func (p *hbcaService) GetSealImage(GetSealImage *GetSealImage) (*GetSealImageResponse, error) {
	α := struct {
		OperationGetSealImage `xml:"tns:getSealImage"`
	}{
		OperationGetSealImage{
			GetSealImage,
		},
	}

	γ := struct {
		OperationGetSealImageResponse `xml:"getSealImageResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("GetSealImage", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetSealImageResponse, nil
}

// GetServerCert was auto-generated from WSDL.
func (p *hbcaService) GetServerCert(GetServerCert *GetServerCert) (*GetServerCertResponse, error) {
	α := struct {
		OperationGetServerCert `xml:"tns:getServerCert"`
	}{
		OperationGetServerCert{
			GetServerCert,
		},
	}

	γ := struct {
		OperationGetServerCertResponse `xml:"getServerCertResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("GetServerCert", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetServerCertResponse, nil
}

// GetServerCertEx was auto-generated from WSDL.
func (p *hbcaService) GetServerCertEx(GetServerCertEx *GetServerCertEx) (*GetServerCertExResponse, error) {
	α := struct {
		OperationGetServerCertEx `xml:"tns:getServerCertEx"`
	}{
		OperationGetServerCertEx{
			GetServerCertEx,
		},
	}

	γ := struct {
		OperationGetServerCertExResponse `xml:"getServerCertExResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("GetServerCertEx", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetServerCertExResponse, nil
}

// GetSignCert was auto-generated from WSDL.
func (p *hbcaService) GetSignCert(GetSignCert *GetSignCert) (*GetSignCertResponse, error) {
	α := struct {
		OperationGetSignCert `xml:"tns:getSignCert"`
	}{
		OperationGetSignCert{
			GetSignCert,
		},
	}

	γ := struct {
		OperationGetSignCertResponse `xml:"getSignCertResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("GetSignCert", α, &γ); err != nil {
		return nil, err
	}
	return γ.GetSignCertResponse, nil
}

// Hello was auto-generated from WSDL.
func (p *hbcaService) Hello(Hello *Hello) (*HelloResponse, error) {
	α := struct {
		OperationHello `xml:"tns:hello"`
	}{
		OperationHello{
			Hello,
		},
	}

	γ := struct {
		OperationHelloResponse `xml:"helloResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("Hello", α, &γ); err != nil {
		return nil, err
	}
	return γ.HelloResponse, nil
}

// ImportEncCert was auto-generated from WSDL.
func (p *hbcaService) ImportEncCert(ImportEncCert *ImportEncCert) (*ImportEncCertResponse, error) {
	α := struct {
		OperationImportEncCert `xml:"tns:importEncCert"`
	}{
		OperationImportEncCert{
			ImportEncCert,
		},
	}

	γ := struct {
		OperationImportEncCertResponse `xml:"importEncCertResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ImportEncCert", α, &γ); err != nil {
		return nil, err
	}
	return γ.ImportEncCertResponse, nil
}

// ImportEncCertForUpdate was auto-generated from WSDL.
func (p *hbcaService) ImportEncCertForUpdate(ImportEncCertForUpdate *ImportEncCertForUpdate) (*ImportEncCertForUpdateResponse, error) {
	α := struct {
		OperationImportEncCertForUpdate `xml:"tns:importEncCertForUpdate"`
	}{
		OperationImportEncCertForUpdate{
			ImportEncCertForUpdate,
		},
	}

	γ := struct {
		OperationImportEncCertForUpdateResponse `xml:"importEncCertForUpdateResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ImportEncCertForUpdate", α, &γ); err != nil {
		return nil, err
	}
	return γ.ImportEncCertForUpdateResponse, nil
}

// ImportSignCert was auto-generated from WSDL.
func (p *hbcaService) ImportSignCert(ImportSignCert *ImportSignCert) (*ImportSignCertResponse, error) {
	α := struct {
		OperationImportSignCert `xml:"tns:importSignCert"`
	}{
		OperationImportSignCert{
			ImportSignCert,
		},
	}

	γ := struct {
		OperationImportSignCertResponse `xml:"importSignCertResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ImportSignCert", α, &γ); err != nil {
		return nil, err
	}
	return γ.ImportSignCertResponse, nil
}

// ImportSignCertForUpdate was auto-generated from WSDL.
func (p *hbcaService) ImportSignCertForUpdate(ImportSignCertForUpdate *ImportSignCertForUpdate) (*ImportSignCertForUpdateResponse, error) {
	α := struct {
		OperationImportSignCertForUpdate `xml:"tns:importSignCertForUpdate"`
	}{
		OperationImportSignCertForUpdate{
			ImportSignCertForUpdate,
		},
	}

	γ := struct {
		OperationImportSignCertForUpdateResponse `xml:"importSignCertForUpdateResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("ImportSignCertForUpdate", α, &γ); err != nil {
		return nil, err
	}
	return γ.ImportSignCertForUpdateResponse, nil
}

// PriKeyDecryptEx was auto-generated from WSDL.
func (p *hbcaService) PriKeyDecryptEx(PriKeyDecryptEx *PriKeyDecryptEx) (*PriKeyDecryptExResponse, error) {
	α := struct {
		OperationPriKeyDecryptEx `xml:"tns:priKeyDecryptEx"`
	}{
		OperationPriKeyDecryptEx{
			PriKeyDecryptEx,
		},
	}

	γ := struct {
		OperationPriKeyDecryptExResponse `xml:"priKeyDecryptExResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("PriKeyDecryptEx", α, &γ); err != nil {
		return nil, err
	}
	return γ.PriKeyDecryptExResponse, nil
}

// PubKeyEncrypt was auto-generated from WSDL.
func (p *hbcaService) PubKeyEncrypt(PubKeyEncrypt *PubKeyEncrypt) (*PubKeyEncryptResponse, error) {
	α := struct {
		OperationPubKeyEncrypt `xml:"tns:pubKeyEncrypt"`
	}{
		OperationPubKeyEncrypt{
			PubKeyEncrypt,
		},
	}

	γ := struct {
		OperationPubKeyEncryptResponse `xml:"pubKeyEncryptResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("PubKeyEncrypt", α, &γ); err != nil {
		return nil, err
	}
	return γ.PubKeyEncryptResponse, nil
}

// PubKeyEncryptEx was auto-generated from WSDL.
func (p *hbcaService) PubKeyEncryptEx(PubKeyEncryptEx *PubKeyEncryptEx) (*PubKeyEncryptExResponse, error) {
	α := struct {
		OperationPubKeyEncryptEx `xml:"tns:pubKeyEncryptEx"`
	}{
		OperationPubKeyEncryptEx{
			PubKeyEncryptEx,
		},
	}

	γ := struct {
		OperationPubKeyEncryptExResponse `xml:"pubKeyEncryptExResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("PubKeyEncryptEx", α, &γ); err != nil {
		return nil, err
	}
	return γ.PubKeyEncryptExResponse, nil
}

// SignData was auto-generated from WSDL.
func (p *hbcaService) SignData(SignData *SignData) (*SignDataResponse, error) {
	α := struct {
		OperationSignData `xml:"tns:signData"`
	}{
		OperationSignData{
			SignData,
		},
	}

	γ := struct {
		OperationSignDataResponse `xml:"signDataResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SignData", α, &γ); err != nil {
		return nil, err
	}
	return γ.SignDataResponse, nil
}

// SignDataByteEx was auto-generated from WSDL.
func (p *hbcaService) SignDataByteEx(SignDataByteEx *SignDataByteEx) (*SignDataByteExResponse, error) {
	α := struct {
		OperationSignDataByteEx `xml:"tns:signDataByteEx"`
	}{
		OperationSignDataByteEx{
			SignDataByteEx,
		},
	}

	γ := struct {
		OperationSignDataByteExResponse `xml:"signDataByteExResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SignDataByteEx", α, &γ); err != nil {
		return nil, err
	}
	return γ.SignDataByteExResponse, nil
}

// SignDataByteEx_raw was auto-generated from WSDL.
func (p *hbcaService) SignDataByteEx_raw(SignDataByteEx_raw *SignDataByteEx_raw) (*SignDataByteEx_rawResponse, error) {
	α := struct {
		OperationSignDataByteEx_raw `xml:"tns:signDataByteEx_raw"`
	}{
		OperationSignDataByteEx_raw{
			SignDataByteEx_raw,
		},
	}

	γ := struct {
		OperationSignDataByteEx_rawResponse `xml:"signDataByteEx_rawResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SignDataByteEx_raw", α, &γ); err != nil {
		return nil, err
	}
	return γ.SignDataByteEx_rawResponse, nil
}

// SignDataEx was auto-generated from WSDL.
func (p *hbcaService) SignDataEx(SignDataEx *SignDataEx) (*SignDataExResponse, error) {
	α := struct {
		OperationSignDataEx `xml:"tns:signDataEx"`
	}{
		OperationSignDataEx{
			SignDataEx,
		},
	}

	γ := struct {
		OperationSignDataExResponse `xml:"signDataExResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SignDataEx", α, &γ); err != nil {
		return nil, err
	}
	return γ.SignDataExResponse, nil
}

// SignDataP7Detach was auto-generated from WSDL.
func (p *hbcaService) SignDataP7Detach(SignDataP7Detach *SignDataP7Detach) (*SignDataP7DetachResponse, error) {
	α := struct {
		OperationSignDataP7Detach `xml:"tns:signDataP7Detach"`
	}{
		OperationSignDataP7Detach{
			SignDataP7Detach,
		},
	}

	γ := struct {
		OperationSignDataP7DetachResponse `xml:"signDataP7DetachResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SignDataP7Detach", α, &γ); err != nil {
		return nil, err
	}
	return γ.SignDataP7DetachResponse, nil
}

// Sm3Hash was auto-generated from WSDL.
func (p *hbcaService) Sm3Hash(Sm3Hash *Sm3Hash) (*Sm3HashResponse, error) {
	α := struct {
		OperationSm3Hash `xml:"tns:sm3Hash"`
	}{
		OperationSm3Hash{
			Sm3Hash,
		},
	}

	γ := struct {
		OperationSm3HashResponse `xml:"sm3HashResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("Sm3Hash", α, &γ); err != nil {
		return nil, err
	}
	return γ.Sm3HashResponse, nil
}

// Sm3HashRaw was auto-generated from WSDL.
func (p *hbcaService) Sm3HashRaw(Sm3HashRaw *Sm3HashRaw) (*Sm3HashRawResponse, error) {
	α := struct {
		OperationSm3HashRaw `xml:"tns:sm3HashRaw"`
	}{
		OperationSm3HashRaw{
			Sm3HashRaw,
		},
	}

	γ := struct {
		OperationSm3HashRawResponse `xml:"sm3HashRawResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("Sm3HashRaw", α, &γ); err != nil {
		return nil, err
	}
	return γ.Sm3HashRawResponse, nil
}

// SymmDataDec was auto-generated from WSDL.
func (p *hbcaService) SymmDataDec(SymmDataDec *SymmDataDec) (*SymmDataDecResponse, error) {
	α := struct {
		OperationSymmDataDec `xml:"tns:symmDataDec"`
	}{
		OperationSymmDataDec{
			SymmDataDec,
		},
	}

	γ := struct {
		OperationSymmDataDecResponse `xml:"symmDataDecResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SymmDataDec", α, &γ); err != nil {
		return nil, err
	}
	return γ.SymmDataDecResponse, nil
}

// SymmDataEnc was auto-generated from WSDL.
func (p *hbcaService) SymmDataEnc(SymmDataEnc *SymmDataEnc) (*SymmDataEncResponse, error) {
	α := struct {
		OperationSymmDataEnc `xml:"tns:symmDataEnc"`
	}{
		OperationSymmDataEnc{
			SymmDataEnc,
		},
	}

	γ := struct {
		OperationSymmDataEncResponse `xml:"symmDataEncResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SymmDataEnc", α, &γ); err != nil {
		return nil, err
	}
	return γ.SymmDataEncResponse, nil
}

// SymmDataEncEx was auto-generated from WSDL.
func (p *hbcaService) SymmDataEncEx(SymmDataEncEx *SymmDataEncEx) (*SymmDataEncExResponse, error) {
	α := struct {
		OperationSymmDataEncEx `xml:"tns:symmDataEncEx"`
	}{
		OperationSymmDataEncEx{
			SymmDataEncEx,
		},
	}

	γ := struct {
		OperationSymmDataEncExResponse `xml:"symmDataEncExResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("SymmDataEncEx", α, &γ); err != nil {
		return nil, err
	}
	return γ.SymmDataEncExResponse, nil
}

// VerifyCertAndSignedData was auto-generated from WSDL.
func (p *hbcaService) VerifyCertAndSignedData(VerifyCertAndSignedData *VerifyCertAndSignedData) (*VerifyCertAndSignedDataResponse, error) {
	α := struct {
		OperationVerifyCertAndSignedData `xml:"tns:verifyCertAndSignedData"`
	}{
		OperationVerifyCertAndSignedData{
			VerifyCertAndSignedData,
		},
	}

	γ := struct {
		OperationVerifyCertAndSignedDataResponse `xml:"verifyCertAndSignedDataResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("VerifyCertAndSignedData", α, &γ); err != nil {
		return nil, err
	}
	return γ.VerifyCertAndSignedDataResponse, nil
}

// VerifyDetachSignData was auto-generated from WSDL.
func (p *hbcaService) VerifyDetachSignData(VerifyDetachSignData *VerifyDetachSignData) (*VerifyDetachSignDataResponse, error) {
	α := struct {
		OperationVerifyDetachSignData `xml:"tns:verifyDetachSignData"`
	}{
		OperationVerifyDetachSignData{
			VerifyDetachSignData,
		},
	}

	γ := struct {
		OperationVerifyDetachSignDataResponse `xml:"verifyDetachSignDataResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("VerifyDetachSignData", α, &γ); err != nil {
		return nil, err
	}
	return γ.VerifyDetachSignDataResponse, nil
}

// VerifyDetachSignDataEx was auto-generated from WSDL.
func (p *hbcaService) VerifyDetachSignDataEx(VerifyDetachSignDataEx *VerifyDetachSignDataEx) (*VerifyDetachSignDataExResponse, error) {
	α := struct {
		OperationVerifyDetachSignDataEx `xml:"tns:verifyDetachSignDataEx"`
	}{
		OperationVerifyDetachSignDataEx{
			VerifyDetachSignDataEx,
		},
	}

	γ := struct {
		OperationVerifyDetachSignDataExResponse `xml:"verifyDetachSignDataExResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("VerifyDetachSignDataEx", α, &γ); err != nil {
		return nil, err
	}
	return γ.VerifyDetachSignDataExResponse, nil
}

// VerifySignedData was auto-generated from WSDL.
func (p *hbcaService) VerifySignedData(VerifySignedData *VerifySignedData) (*VerifySignedDataResponse, error) {
	α := struct {
		OperationVerifySignedData `xml:"tns:verifySignedData"`
	}{
		OperationVerifySignedData{
			VerifySignedData,
		},
	}

	γ := struct {
		OperationVerifySignedDataResponse `xml:"verifySignedDataResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("VerifySignedData", α, &γ); err != nil {
		return nil, err
	}
	return γ.VerifySignedDataResponse, nil
}

// VerifySignedDataP1 was auto-generated from WSDL.
func (p *hbcaService) VerifySignedDataP1(VerifySignedDataP1 *VerifySignedDataP1) (*VerifySignedDataP1Response, error) {
	α := struct {
		OperationVerifySignedDataP1 `xml:"tns:verifySignedDataP1"`
	}{
		OperationVerifySignedDataP1{
			VerifySignedDataP1,
		},
	}

	γ := struct {
		OperationVerifySignedDataP1Response `xml:"verifySignedDataP1Response"`
	}{}
	if err := p.cli.RoundTripWithAction("VerifySignedDataP1", α, &γ); err != nil {
		return nil, err
	}
	return γ.VerifySignedDataP1Response, nil
}

// VerifySignedDataP1Byte was auto-generated from WSDL.
func (p *hbcaService) VerifySignedDataP1Byte(VerifySignedDataP1Byte *VerifySignedDataP1Byte) (*VerifySignedDataP1ByteResponse, error) {
	α := struct {
		OperationVerifySignedDataP1Byte `xml:"tns:verifySignedDataP1Byte"`
	}{
		OperationVerifySignedDataP1Byte{
			VerifySignedDataP1Byte,
		},
	}

	γ := struct {
		OperationVerifySignedDataP1ByteResponse `xml:"verifySignedDataP1ByteResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("VerifySignedDataP1Byte", α, &γ); err != nil {
		return nil, err
	}
	return γ.VerifySignedDataP1ByteResponse, nil
}

// VerifyTimeStamp was auto-generated from WSDL.
func (p *hbcaService) VerifyTimeStamp(VerifyTimeStamp *VerifyTimeStamp) (*VerifyTimeStampResponse, error) {
	α := struct {
		OperationVerifyTimeStamp `xml:"tns:verifyTimeStamp"`
	}{
		OperationVerifyTimeStamp{
			VerifyTimeStamp,
		},
	}

	γ := struct {
		OperationVerifyTimeStampResponse `xml:"verifyTimeStampResponse"`
	}{}
	if err := p.cli.RoundTripWithAction("VerifyTimeStamp", α, &γ); err != nil {
		return nil, err
	}
	return γ.VerifyTimeStampResponse, nil
}
